// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { Login2Data, Login2Errors, LoginData, LoginErrors, LoginResponses, PingData, PingResponses, RedirectData, RedirectErrors, ResetPasswordData, ResetPasswordErrors, ResetPasswordRequestData, ResetPasswordRequestErrors, ResetPasswordRequestResponses, ResetPasswordResponses, SignUpData, SignUpErrors, SignUpResponses, VerifyEmailData, VerifyEmailErrors, VerifyEmailResponses, WhoamiData, WhoamiErrors, WhoamiResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health check endpoint
 *
 * Returns a simple message to verify the service is running.
 */
export const ping = <ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>): RequestResult<PingResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/ping',
    ...options
});

/**
 * User registration endpoint
 *
 * Allows a new user to register by providing their details.
 */
export const signUp = <ThrowOnError extends boolean = false>(options: Options<SignUpData, ThrowOnError>): RequestResult<SignUpResponses, SignUpErrors, ThrowOnError> => (options.client ?? client).post<SignUpResponses, SignUpErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * User login endpoint
 *
 * Allows a registered user to log in by providing their credentials.
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get current user information
 *
 * Returns the information of the currently authenticated user.
 */
export const whoami = <ThrowOnError extends boolean = false>(options?: Options<WhoamiData, ThrowOnError>): RequestResult<WhoamiResponses, WhoamiErrors, ThrowOnError> => (options?.client ?? client).get<WhoamiResponses, WhoamiErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/whoami',
    ...options
});

/**
 * Verify email endpoint
 *
 * Allows a registered user to verify their email by providing their verification token.
 */
export const verifyEmail = <ThrowOnError extends boolean = false>(options: Options<VerifyEmailData, ThrowOnError>): RequestResult<VerifyEmailResponses, VerifyEmailErrors, ThrowOnError> => (options.client ?? client).post<VerifyEmailResponses, VerifyEmailErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/verify-email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request to reset password endpoint
 *
 * Allows a registered user to request to reset their password.
 */
export const resetPasswordRequest = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordRequestData, ThrowOnError>): RequestResult<ResetPasswordRequestResponses, ResetPasswordRequestErrors, ThrowOnError> => (options.client ?? client).post<ResetPasswordRequestResponses, ResetPasswordRequestErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/reset-password-request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset password endpoint
 *
 * Allows a user to set a new password by providing the reset token received by email and their new password.
 */
export const resetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetPasswordData, ThrowOnError>): RequestResult<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError> => (options.client ?? client).post<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Initiate Google OAuth login
 *
 * Redirects the user to the Google OAuth consent screen to begin the authentication flow.
 */
export const login2 = <ThrowOnError extends boolean = false>(options?: Options<Login2Data, ThrowOnError>): RequestResult<unknown, Login2Errors, ThrowOnError> => (options?.client ?? client).get<unknown, Login2Errors, ThrowOnError>({ url: '/auth/google/login', ...options });

/**
 * Google OAuth callback
 *
 * Handles the redirect from Google after authentication. Generates a JWT token and redirects the user to the UI with the token as a query parameter.
 */
export const redirect = <ThrowOnError extends boolean = false>(options?: Options<RedirectData, ThrowOnError>): RequestResult<unknown, RedirectErrors, ThrowOnError> => (options?.client ?? client).get<unknown, RedirectErrors, ThrowOnError>({ url: '/auth/google/redirect', ...options });
