// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type PingResponse = {
    /**
     * The message returned in the ping response
     */
    message: string;
};

export type SignupRequest = {
    email: string;
    pseudo: string;
    name: string;
    password: string;
    /**
     * Optional avatar URL for the user
     */
    avatar?: string;
};

export type UserResponse = {
    /**
     * Unique identifier of the user
     */
    id: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * Pseudonym of the user
     */
    pseudo: string;
    /**
     * Full name of the user
     */
    name: string;
    /**
     * URL of the user's avatar image
     */
    avatar: {
        [key: string]: unknown;
    } | null;
    /**
     * Whether the user's email has been verified
     */
    isEmailVerified: boolean;
    /**
     * Whether the user is authenticated with Google
     */
    isOAuthGoogleProvider: boolean;
    /**
     * Timestamp when the user was created
     */
    createdAt: string;
    /**
     * Timestamp when the user was last updated
     */
    updatedAt: string;
    /**
     * Role of the user
     */
    role: 'USER' | 'ADMIN';
};

export type HttpExceptionResponse = {
    /**
     * HTTP status code
     */
    status: number;
    /**
     * Error type
     */
    type: string;
    /**
     * Error message
     */
    message: string;
    /**
     * Timestamp of the error
     */
    timestamp: string;
    /**
     * Request path that caused the error
     */
    path: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    /**
     * JWT Token for authentication
     */
    token: string;
    /**
     * User profile
     */
    user: UserResponse;
};

export type VerifyEmailRequest = {
    /**
     * User email verification token
     */
    emailVerificationToken: string;
};

export type ResetPasswordRequestRequest = {
    /**
     * User email address
     */
    email: string;
};

export type ResetPasswordRequestResponse = {
    /**
     * User email address
     */
    email: string;
};

export type ResetPasswordRequest = {
    /**
     * The password reset token received by email
     */
    resetPasswordToken: string;
    /**
     * The new password to set for the account
     */
    newPassword: string;
};

export type PingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The message to be sent in the ping request
         */
        message?: string;
    };
    url: '/ping';
};

export type PingResponses = {
    /**
     * Service is running
     */
    200: PingResponse;
};

export type PingResponse2 = PingResponses[keyof PingResponses];

export type SignUpData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type SignUpErrors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type SignUpError = SignUpErrors[keyof SignUpErrors];

export type SignUpResponses = {
    /**
     * User successfully registered
     */
    201: UserResponse;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * User successfully logged in
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type WhoamiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/whoami';
};

export type WhoamiErrors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type WhoamiError = WhoamiErrors[keyof WhoamiErrors];

export type WhoamiResponses = {
    /**
     * Current user information
     */
    200: UserResponse;
};

export type WhoamiResponse = WhoamiResponses[keyof WhoamiResponses];

export type VerifyEmailData = {
    body: VerifyEmailRequest;
    path?: never;
    query?: never;
    url: '/auth/verify-email';
};

export type VerifyEmailErrors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * User email successfully verified
     */
    200: UserResponse;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResetPasswordRequestData = {
    body: ResetPasswordRequestRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password-request';
};

export type ResetPasswordRequestErrors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type ResetPasswordRequestError = ResetPasswordRequestErrors[keyof ResetPasswordRequestErrors];

export type ResetPasswordRequestResponses = {
    /**
     * Password reset email sent — returns the email address
     */
    200: ResetPasswordRequestResponse;
};

export type ResetPasswordRequestResponse2 = ResetPasswordRequestResponses[keyof ResetPasswordRequestResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordErrors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Password successfully reset — returns the updated user
     */
    200: UserResponse;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type Login2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/login';
};

export type Login2Errors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type Login2Error = Login2Errors[keyof Login2Errors];

export type RedirectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/redirect';
};

export type RedirectErrors = {
    /**
     * Bad Request - The request could not be understood or was missing required parameters.
     */
    400: HttpExceptionResponse;
    /**
     * Forbidden - The server understood the request, but refuses to authorize it.
     */
    403: HttpExceptionResponse;
    /**
     * Not Found - The requested resource could not be found on the server.
     */
    404: HttpExceptionResponse;
    /**
     * Too Many Requests - The user has sent too many requests in a given amount of time.
     */
    429: HttpExceptionResponse;
    /**
     * Internal Server Error - An unexpected condition was encountered by the server.
     */
    500: HttpExceptionResponse;
};

export type RedirectError = RedirectErrors[keyof RedirectErrors];
