import type { DonaEvent } from '@/types/map';

/**
 * Real-time Road Incident Signals (Waze-style crowdsourced alerts for Dona).
 * Includes road accidents, traffic jams, police controls, hazards, and road closures
 * in Antananarivo (Madagascar) and Paris.
 */
export const MOCK_DONA_EVENTS: DonaEvent[] = [
	{
		id: 'evt-tana-1',
		title: 'Accident grave — Collision 2 véhicules',
		description:
			'Accident entre un taxi-be et une voiture légère. Voie de droite complètement bloquée, forts ralentissements vers Analakely.',
		location: { lat: -18.9101, lng: 47.5256 },
		addressName: 'Avenue de l’Indépendance, Analakely, Antananarivo',
		category: 'accident',
		severity: 'major',
		status: 'active',
		veracityScore: 94,
		confirmationsCount: 18,
		resolutionsCount: 1,
		isOfficialValidated: true,
		createdAt: 'Il y a 12 min',
		reportedBy: {
			name: 'Rasoa Driver',
			avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop',
			reputationScore: 480,
		},
		imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&auto=format&fit=crop',
	},
	{
		id: 'evt-tana-2',
		title: 'Embouteillage Monstre — Trafic presque à l’arrêt',
		description:
			'Bouchon très dense autour du rond-point du Lac Anosy vers Mahamasina. Temps de traversée estimé : 35 minutes.',
		location: { lat: -18.9133, lng: 47.5218 },
		addressName: 'Rond-point Lac Anosy, Antananarivo 101',
		category: 'traffic_jam',
		severity: 'moderate',
		status: 'active',
		veracityScore: 88,
		confirmationsCount: 24,
		resolutionsCount: 2,
		isOfficialValidated: false,
		createdAt: 'Il y a 25 min',
		reportedBy: {
			name: 'Haja Commuter',
			reputationScore: 210,
		},
	},
	{
		id: 'evt-tana-3',
		title: 'Contrôle Police & Vérification Papiers',
		description: 'Contrôle de police fixe des deux côtés du boulevard. Ralentissement préalable à prévoir.',
		location: { lat: -18.9056, lng: 47.5322 },
		addressName: 'Boulevard de Ankorondrano, Antananarivo',
		category: 'police',
		severity: 'minor',
		status: 'active',
		veracityScore: 96,
		confirmationsCount: 31,
		resolutionsCount: 0,
		isOfficialValidated: true,
		createdAt: 'Il y a 8 min',
		reportedBy: {
			name: 'Police Nationale (Officiel)',
			reputationScore: 1500,
		},
	},
	{
		id: 'evt-tana-4',
		title: 'Danger — Chaussée glissante & Nids de poule',
		description:
			'Trou important sur la voie de gauche suite aux récentes pluies. Risque d’endommagement de suspension.',
		location: { lat: -18.8872, lng: 47.5144 },
		addressName: 'Route d’Ivato / Talatamaty, Antananarivo',
		category: 'hazard',
		severity: 'moderate',
		status: 'active',
		veracityScore: 82,
		confirmationsCount: 12,
		resolutionsCount: 1,
		createdAt: 'Il y a 45 min',
		reportedBy: {
			name: 'Andry Moto',
			reputationScore: 340,
		},
	},
	{
		id: 'evt-tana-5',
		title: 'Route fermée — Travaux de réfection du pont',
		description: 'Route barrée pour travaux d’enrobé. Déviation mise en place par la rue parallèle.',
		location: { lat: -18.9245, lng: 47.5412 },
		addressName: 'Route de Tanjombato, Antananarivo',
		category: 'closure',
		severity: 'major',
		status: 'active',
		veracityScore: 100,
		confirmationsCount: 45,
		resolutionsCount: 0,
		isOfficialValidated: true,
		createdAt: 'Il y a 2h',
		reportedBy: {
			name: 'Ministère des Travaux Publics',
			reputationScore: 2000,
		},
	},
	{
		id: 'evt-paris-1',
		title: 'Accident — Collison 3 véhicules',
		description: 'Voie de gauche neutralisée sur le Périphérique extérieur.',
		location: { lat: 48.8566, lng: 2.3522 },
		addressName: 'Boulevard Périphérique, Porte de Charenton, Paris',
		category: 'accident',
		severity: 'major',
		status: 'active',
		veracityScore: 92,
		confirmationsCount: 29,
		resolutionsCount: 3,
		isOfficialValidated: true,
		createdAt: 'Il y a 15 min',
		reportedBy: {
			name: 'Jean Driver',
			reputationScore: 620,
		},
	},
	{
		id: 'evt-paris-2',
		title: 'Ralentissement important — Bouchon 4 km',
		description: 'Bouchon de l’accordéon suite à des travaux de voirie.',
		location: { lat: 48.8462, lng: 2.3372 },
		addressName: 'Boulevard Saint-Michel, 75006 Paris',
		category: 'traffic_jam',
		severity: 'moderate',
		status: 'active',
		veracityScore: 85,
		confirmationsCount: 15,
		resolutionsCount: 1,
		createdAt: 'Il y a 30 min',
		reportedBy: {
			name: 'Marie VTC',
			reputationScore: 410,
		},
	},
];
